apiVersion: v1
kind: Service
metadata:
  name: cfcc-controller
  labels:
    app: cfcc-controller
spec:
  selector:
    app: cfcc-controller
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: {{ .Values.controller.service.targetPort }}
      protocol: TCP
      name: http
