apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: controller-tls
  namespace: digicred-traction
spec:
  secretName: controller-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: controllersprod.digicred.services
  dnsNames:
  - controllersprod.digicred.services